name = "EvolutionaryStrategies"
uuid = "0db62460-6af5-4b1a-9d1c-927487bb80c6"
authors = ["Dennis Wilson <d9w@pm.me>"]
version = "0.1.0"

[deps]
Cambrian = "7f27c84d-2d74-42e5-be5f-94f6748267f3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Cambrian = "0.2.0"